Feature fix for Ideal schedule names
leapwork/TeamCity-plugin pull request #11
Opened 2021-09-13 11:15 UTC by BirSikanderMahajan

Updated getSchedulesIdTitleHashMap in Plugin Handler class, now it will not return the schedule id of disabled Schedule having same name.

2021-09-14 09:04 UTC, AntonLiakhovich requested changes
- what happens if there are two (or three) Schedules with identical names in different Run Lists?
- we agreed to not upload binaries to repository

2021-09-14 09:18 UTC, BirSikanderMahajan commented
The logic will take care of the schedules having same name in different run lists. If all of them are enabled it will run those schedules, if any of them is disabled It will not run that schedule.
Leapwork doesn't allow same names in one run list.

I have removed target folder from the repo, build folder is required for packaging in future. Removing target folder from build folder.

2021-09-14 09:51 UTC, AntonLiakhovich commented
> The logic will take care of the schedules having same name in different run lists. If all of them are enabled it will run those schedules, if any of them is disabled It will not run that schedule.
> Leapwork doesn't allow same names in one run list.
> 
> I have removed target folder from the repo, build folder is required for packaging in future. Removing target folder from build folder.

that's what I asked. is it expected behavior to run all Schedules with identical names? the story you had to work on clearly explains waht must happen in this scenario

2021-09-14 09:56 UTC, BirSikanderMahajan commented
@AntonLiakhovich, it will not run all the schedules if one Schedule is selected. It will only run schedule with that particular schedule Id. So, if you want to run all schedules you need to select schedule names.

![image](https://user-images.githubusercontent.com/83980204/133237025-f1626258-1123-4027-8379-3732bdda2512.png)

2021-09-14 10:12 UTC, AntonLiakhovich commented
> @AntonLiakhovich, it will not run all the schedules if one Schedule is selected. It will only run schedule with that particular schedule Id. So, if you want to run all schedules you need to select schedule names.
> 
> ![image](https://user-images.githubusercontent.com/83980204/133237025-f1626258-1123-4027-8379-3732bdda2512.png)

once again, what happens if in this case there are ten (10) enabled schedules with "Open Amazon" name?
![image](https://user-images.githubusercontent.com/72276668/133239195-b94114ce-0099-4975-ad01-a44446aa6076.png)

2021-09-14 10:18 UTC, BirSikanderMahajan commented
In the above case, it will execute those schedules (openAmazon) which have been selected out of 10 schedules.
Every Schedule in OpenAmazon have different ScheduleId and run api accepts the schedule id.

2021-09-14 11:58 UTC, AntonLiakhovich commented
> In the above case, it will execute those schedules (openAmazon) which have been selected out of 10 schedules.
> Every Schedule in OpenAmazon have different ScheduleId and run api accepts the schedule id.

So I checked the code. It is possible just define Schedule name without selecting id and it will be saved. Next time all schedules with this name across all Run Lists will be executed. As mentioned in the task we need to prevent it from happening.

2021-09-14 13:36 UTC, BirSikanderMahajan commented
As per the reported issue.
If there are two or more identical name of schedules in different run lists, and one of them was disabled, it executes the disabled schedule and Fail the execution with response "Schedule is disabled", because getSchedulesIdTitleHashMap method has logic in which it will first map the schedule Id and then the title.
So, now we have updated the logic in which it will not execute the disabled schedules.

2021-10-11 06:08 UTC, BharatJawal commented on leapwork-integration-agent/src/main/java/com/leapwork/leapwork_integration/PluginHandler.java
> +		ArrayList<String> tempList = new ArrayList<>(rawScheduleList);
use variable name as per there uses.

2021-10-11 06:08 UTC, BharatJawal commented on leapwork-integration-common/src/main/java/com/leapwork/leapwork_integration/Messages.java
> +    public static final String NO_SUCH_SCHEDULE = "No such schedule This may occur if try to run schedule that controller does not have. It can be deleted. Or you simply have forgotten to select sche
No such schedule, this may occur if try to run schedule that controller does not have.

2021-10-11 10:18 UTC, BirSikanderMahajan commented on leapwork-integration-agent/src/main/java/com/leapwork/leapwork_integration/PluginHandler.java
> +		ArrayList<String> tempList = new ArrayList<>(rawScheduleList);
Changes the variable name to tempRawScheduleList

2021-10-11 10:18 UTC, BirSikanderMahajan commented on leapwork-integration-common/src/main/java/com/leapwork/leapwork_integration/Messages.java
> +    public static final String NO_SUCH_SCHEDULE = "No such schedule This may occur if try to run schedule that controller does not have. It can be deleted. Or you simply have forgotten to select sche
Added ! sign in the messages class

2021-10-11 10:22 UTC, AntonLiakhovich requested changes
Check my comments

2021-10-11 10:22 UTC, AntonLiakhovich commented on leapwork-integration-common/src/main/java/com/leapwork/leapwork_integration/Messages.java
> +    public static final String COULD_NOT_CONNECT_TO = "Could not connect to %1$s! Check it and try again";
do not use _!_ in messages shown for user

2021-10-11 10:22 UTC, AntonLiakhovich commented on leapwork-integration-server/src/main/resources/buildServerResources/buttonscript.js
> +			alert('"hostname or/and field is empty! Cannot connect to controller!"');
the same here, exclamation mark is not user friendly

2021-10-18 06:11 UTC, BirSikanderMahajan commented on leapwork-integration-server/src/main/resources/buildServerResources/buttonscript.js
> +			alert('"hostname or/and field is empty! Cannot connect to controller!"');
this have been removed

2021-10-18 06:12 UTC, BirSikanderMahajan commented on leapwork-integration-common/src/main/java/com/leapwork/leapwork_integration/Messages.java
> +    public static final String COULD_NOT_CONNECT_TO = "Could not connect to %1$s! Check it and try again";
Removed "!" from the messages

2021-10-18 06:23 UTC, BharatJawal submitted a review, later dismissed

2021-10-26 09:01 UTC, AntonLiakhovich requested changes
a few more places

2021-10-26 09:01 UTC, AntonLiakhovich commented on leapwork-integration-server/src/main/resources/buildServerResources/buttonscript.js
> +			alert('"hostname or/and field is empty! Cannot connect to controller"');
what about this one?

2021-10-26 09:01 UTC, AntonLiakhovich commented on leapwork-integration-server/src/main/resources/buildServerResources/buttonscript.js
> +                                "Error occurred! Cannot get the list of Schedules\n" +
the same here

2021-10-26 09:34 UTC, BirSikanderMahajan commented on leapwork-integration-server/src/main/resources/buildServerResources/buttonscript.js
> +                                "Error occurred! Cannot get the list of Schedules\n" +
this one also, removed ! sign

2021-10-26 09:34 UTC, BirSikanderMahajan commented on leapwork-integration-server/src/main/resources/buildServerResources/buttonscript.js
> +			alert('"hostname or/and field is empty! Cannot connect to controller"');
in this, its updated already.

2021-10-27 07:55 UTC, AntonLiakhovich approved these changes
Approved

2021-10-27 08:17 UTC, merged