Featurebranch adding csp
leapwork/TeamCity-plugin pull request #4
Opened 2021-06-01 12:27 UTC by BirSikanderMahajan

have added the following:
1. csp header
2. leaptest to Leapwork
3. customatics to Leapwork
4. added name, url and email

2021-06-04 04:36 UTC, RishiGaurav commented on README.md
> +This is LEAPWORK plugin for Teamcity
Change all block letter LEAPWORK to Leapwork.

2021-06-04 04:39 UTC, RishiGaurav commented on teamcity-plugin.xml
> +    <email>info-emea@leapwork.com</email>
Change email to: prioritysupport@leapwork.com

2021-06-07 10:57 UTC, RomanSyrychLeapwork commented on build/pom.xml
> +    <version>0.0.1-SNAPSHOT</version>
I think this should be the same as plugin version 4.0.1

2021-06-07 10:57 UTC, RomanSyrychLeapwork commented on build/pom.xml
> +           <version>0.0.1-SNAPSHOT</version>
I think this should be the same as plugin version 4.0.1

2021-06-07 10:58 UTC, RomanSyrychLeapwork commented on build/pom.xml
> +           <version>0.0.1-SNAPSHOT</version>
I think this should be the same as plugin version 4.0.1

2021-06-07 10:58 UTC, RomanSyrychLeapwork commented on build/pom.xml
> +           <version>0.0.1-SNAPSHOT</version>
I think this should be the same as plugin version 4.0.1

2021-06-07 10:59 UTC, RomanSyrychLeapwork commented on leapwork-integration-agent/pom.xml
> +    <version>0.0.1-SNAPSHOT</version>
I think this should be the same as plugin version 4.0.1

2021-06-07 10:59 UTC, RomanSyrychLeapwork commented on leapwork-integration-agent/pom.xml
> +      <version>0.0.1-SNAPSHOT</version>
I think this should be the same as plugin version 4.0.1

2021-06-07 11:05 UTC, RomanSyrychLeapwork commented on leapwork-integration-agent/src/main/java/com/leapwork/leapwork_integration/FutureBasedBuildProcess.java
> +    private Future<BuildFinishedStatus> myFuture;
Please rename `myFuture `to something like `RunPluginExecution`

2021-06-07 11:06 UTC, RomanSyrychLeapwork commented on leapwork-integration-agent/src/main/java/com/leapwork/leapwork_integration/InvalidSchedule.java
> +/**
Please remove this redundant comment

2021-06-07 11:28 UTC, RomanSyrychLeapwork commented on leapwork-integration-agent/src/main/java/com/leapwork/leapwork_integration/Utils.java
> +/**
Please remove this redundant comment

2021-06-07 11:29 UTC, RomanSyrychLeapwork commented on leapwork-integration-common/pom.xml
> +    <version>0.0.1-SNAPSHOT</version>
I think this should be the same as plugin version 4.0.1

2021-06-07 11:30 UTC, RomanSyrychLeapwork commented on leapwork-integration-common/src/main/java/com/leapwork/leapwork_integration/Failure.java
> +/**
Please remove this redundant comment

2021-06-07 11:45 UTC, RomanSyrychLeapwork commented on leapwork-integration-common/src/main/java/com/leapwork/leapwork_integration/RunItem.java
> +/**
Please remove redundant commit

2021-06-07 11:46 UTC, RomanSyrychLeapwork commented on leapwork-integration-common/src/main/java/com/leapwork/leapwork_integration/TeamcityServiceMessagesFormatter.java
> +/**
Please remove redundant comments

2021-06-07 11:46 UTC, RomanSyrychLeapwork commented on leapwork-integration-server/pom.xml
> +    <version>0.0.1-SNAPSHOT</version>
I think this should be the same as plugin version 4.0.1

2021-06-07 11:46 UTC, RomanSyrychLeapwork commented on leapwork-integration-server/pom.xml
> +      <version>0.0.1-SNAPSHOT</version>
I think this should be the same as plugin version 4.0.1

2021-06-07 11:48 UTC, RomanSyrychLeapwork commented on leapwork-integration-server/src/main/java/com/leapwork/leapwork_integration/Utils.java
> +/**
Please remove redundant commit

2021-06-07 11:48 UTC, RomanSyrychLeapwork commented on pom.xml
> +  <version>0.0.1-SNAPSHOT</version>
I think this should be the same as plugin version 4.0.1

2021-06-07 14:27 UTC, AntonLiakhovich commented on teamcity-plugin.xml
> +    <email>info-emea@leapwork.com</email>
good idea

2021-06-10 08:10 UTC, AntonLiakhovich requested changes
see my comments

2021-06-10 08:10 UTC, AntonLiakhovich commented on README.md
> +# Update 3.1.1
I believe this should be removed because it is a new clean version

2021-06-10 08:10 UTC, AntonLiakhovich commented on README.md
> +LEAPWORK is a mighty automation testing system and now it can be used for running [smoke, functional, acceptance] tests, generating reports and a lot more in Teamcity. You can easily configure integr
Change LEAPWORK to Leapwork

2021-06-15 08:16 UTC, closed without merging

2021-06-15 08:16 UTC, AntonLiakhovich commented
PR is closed because a new one is created